### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by bondvt04** [CytoDev/PixelCircleGenerator#13]
So I want to use this for drawing circle in my RimWorld layout. How to do this? :)
Obviously I have to do it manually, so I need to copy pixel by pixel from the result of this app to my RimWorld window. BUT. We can't zoom into and see how many pixels that particular row takes. Example - how many pixels in the bottom line?
https://image.prntscr.com/image/KIRcCteARle34bZmK1qmhA.png

**Comment by cytodev** [comment]
Hi @bondvt04,

I'm terribly sorry it took me more than a week to respond to your issue!

When I wrote the script that powers this web-application the [`PointerEvent` API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) wasn't implemented in most mayor browsers yet. This lead me to (falsely) assume that this API was mobile only, and I never set up the `DOMMouseScroll` and `mousewheel` listeners within that block ([see these lines](https://github.com/CytoDev/PixelCircleGenerator/blob/v0.1.3/application/script/pcg.js#L440-L457)).

I have set them up now though, so this issue should be fixed.
